

= Code lists and business rules
:icons: font

// First unset attribute to remotely link FontAwesome CSS
:iconfont-remote!:

// Specify name of FontAwesome CSS.
:iconfont-name: fontawesome-4.1.0

// We can optionally set the directory where CSS is stored.
:stylesdir: css


include::../attributes.adoc[]

#Add link to BII documents#

The piloting of {eSENS} for Submit Tender, is based on work done by {CENBII}, and business rules and code lists used are inherited from the follwing {CENBII} documents:

* CWA3456 Part 218 UBL SIG - Trdm090 Tender.docx
* CWA3456 Part 205 UBL SIG - Trdm045 Tender Reception Notification.docx
* CWA3456 Part 119 Profile 54 - Tendering.docx

IMPORTANT: The profile document and syntax implementation guides from {CENBII} must be considered when implementing Submit Tender based on this BIS document

In addition to the rules and code lists from the {CENBII} work, the {eSENS}  pilot is using {PEPPOL} Transport infrastructure, and some additional business rules has been added, to ensure correct use according to {PEPPOL} Policies. The testing/piloting has also revealed that there where a few other rules/code lists needed as validation artefacts to ensure an instance document is conformant with the {CENBII} specifications.

The following chapters gives an overview of any code lists and business rules added by the {eSENS} pilot project. For rules and code lists from {CENBII}, we refer to the published documents above.
